### ISSUE TITLE
Error in helm template when openfga is used as dependency and has global property in values

### ISSUE THREAD

**Issue by jgpelaez** [openfga/helm-charts#106]
In latest version of the helm chart (0.1.36) there is schema validation on the chart, problem comes when we are using openfga as dependency:

```yaml
dependencies:
- name: openfga
  version: 0.1.36
  repository: https://openfga.github.io/helm-charts
  alias: openfga
  condition: enabled
```

It is possible that in the main chart we are using `global` properties for use in other charts, and we got the error:

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
openfga:
- (root): Additional property global is not allowed
```

This can be solved adding to the schema the global as parameter.
