### ISSUE TITLE
Migrate job not showing up in ArgoCD

### ISSUE THREAD

**Issue by supercairos** [openfga/helm-charts#107]
There is an issue with OpenFGA helm chart when it's used with ArgoCD.

Migrate job doesn't show up on ArgoCD and is not created by ArgoCD.

This is due to the default `helm hooks` in place in the migrate job defined in the default values.yaml of this helm charts:
https://github.com/openfga/helm-charts/blob/main/charts/openfga/values.yaml#L269-L271

```
migrate:
  annotations:
    helm.sh/hook: "post-install, post-upgrade, post-rollback, post-delete"
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: "before-hook-creation"
```

The current workaround is to disable them like this in one of your child charts:
```
migrate:
  annotations:
    helm.sh/hook: null
    helm.sh/hook-weight: null
    helm.sh/hook-delete-policy: null
```

Could we remove them ?

**Comment by supercairos** [comment]
It seams that ArgoCD doesn't understand `post-rollback`. Removing it should fix the issue:

```
migrate:
  annotations:
    helm.sh/hook: "post-install, post-upgrade, post-delete"
```

**Comment by nikonet** [comment]
Hello.

I found a way to make this work using ArgoCD's built-in sync waves.

I use Helm in Kustomize like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openfga

helmCharts:
- name: openfga
  repo: https://openfga.github.io/helm-charts
  version: 0.2.3
  releaseName: openfga
  namespace: openfga
  valuesFile: values.yaml
```

And the full helm values:

```yaml
replicaCount: 1

datastore:
  engine: postgres
  uriSecret: pg-uri
  
serviceAccount: # Requires existing before the migrations job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"

migrate:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
```

For reference I'm using [CNPG](https://cloudnative-pg.io/documentation/1.16/) (postgres 14.11) as postgres operator and external-secrets-operator to create a shared secret for the pg username, password and uri.
