### ISSUE TITLE
datastore.applyMigrations value is not working

### ISSUE THREAD

**Issue by jpnorenam** [openfga/helm-charts#161]
`openfga-migrate` BatchJob is not getting created for some reason. As a workaround, I had to go to the `openfga` ReplicaSet and modify the `openfga` container arguments from `run` to `migrate` to get the migration done, then change it back to `run`.

```
source:
  repoURL: https://openfga.github.io/helm-charts
  targetRevision: 0.2.13
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: service.type
        value: ClusterIP
      - name: datastore.engine
        value: postgres
      - name: datastore.uri
        value: >-
          postgres://postgres:password@openfga-postgresql.openfga.svc.cluster.local:5432/postgres?sslmode=disable
      - name: postgresql.enabled
        value: 'true'
      - name: postgresql.auth.postgresPassword
        value: password
      - name: postgresql.auth.database
        value: postgres
      - name: datastore.waitForMigrations
        value: 'false'
      - name: replicaCount
        value: '1'
      - name: datastore.applyMigrations
        value: 'true'
  chart: openfga
```

**Comment by 98jan** [comment]
I set in the values.yaml following entry, then the migration did work:

```
  datastore:
    engine: postgres
    uri: "..."
    migrationType: "job"
```
