### ISSUE TITLE
Feat: Add a convenient way to mount preshared keys from secrets

### ISSUE THREAD

**Issue by c-thiel** [openfga/helm-charts#175]

**Comment by grimly** [comment]
Hello,

Here is an example of your use-case

```yaml
authn:
  method: preshared

extraEnvVars:
  - name: OPENFGA_AUTHN_PRESHARED_KEYS
    valueFrom:
      secretKeyRef:
        name: your-secret
        key: your-key
```

Make sure you do not have anything in `.Values.authn.preshared.keys`.

I also had more constraints regarding this injection as I had to use the Vault provider and the CSI driver, which requires the secret also to be loaded as in a volume. Here the configuration would be a bit more involved but still doable in the chart values :

```yaml
authn:
  method: preshared

extraEnvVars:
  - name: OPENFGA_AUTHN_PRESHARED_KEYS
    valueFrom:
      secretKeyRef:
        name: your-secret
        key: your-key
extraVolumes:
  - name: your-secret-volume
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: your-secret-provider-class
extraVolumeMounts:
  - name: your-secret-volume
    mountPath: /your/mount/path
    readOnly: true
extraObjects:
  - apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
      name: your-secret-provider-class
    spec:
      provider: vault
      secretObjects:
        - data:
          - key: your-object-name
            objectName: your-key
          secretName: your-secret
          type: Opaque
      parameters:
        vaultAddress: "https://vault"
        objects: |
          - objectName: your-object-name
            secretPath: "your/secret/path/in/vault"
            secretKey: your-vault-key
```
