### ISSUE TITLE
Initial chart deployment fails: Error from server (NotFound): jobs.batch "openfga-migrate" not found

### ISSUE THREAD

**Issue by malud** [openfga/helm-charts#211]
So basically our setup is ArgoCD which polls the gitops repo to apply this helm chart. However, the openfga pod fails with `Back-off restarting failed container wait-for-migration in pod openfga`.
This happens due to the missing job.

This resource doesn’t get created automatically — I have to log in to our cluster and apply the job resource manually in order for the migrate init container to succeed, which in turn allows the FGA pod to run.

The job resource is the only one with a hook and weight annotation:

`helm.sh/hook-weight: "-5"` 

Could this be the issue?

**Comment by jonasmock** [comment]
@malud Any recommendations how to fix it? Does it work with older verisons. I try to setup openfga via Helm chart in our Kubernetes.

**Comment by marlenekoh** [comment]
adding helm annotations to the service account and migrate job to create them during `pre-install` fixed it for me

```yaml
# in values.yaml

serviceAccount:
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "-10" # create svc acc before migrate job

migrate:
  annotations:
    helm.sh/hook: "pre-install, post-upgrade, post-rollback, post-delete" # not post-install
    helm.sh/hook-weight: "-5"
```

**Comment by mkyc** [comment]
Related to #107. 

This is related how ArgoCD interprets some of Helm hooks. I did local helm install first and then after chart is applied once all works well via ArgoCD.

**Comment by RhynoVDS** [comment]
This did not work for me. What worked for me was to remove the annotations on migrate and set serviceAccount hooks as follows.

```
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "-6"

migrate:
  annotations:
```

With this setting, the openFGA service pods wait for the migrate pod to finish running. After the migrate pod finishes the service pods start successfully.
