### ISSUE TITLE
allow pulling datastore uri from kubernetes secret

### ISSUE THREAD

**Issue by neeraj-ec** [openfga/helm-charts#26]
For `postgres` or `mysql` datastore, chart needs full db uri along with username and password. Considering `gitOps` we would not want to expose DB password in the git repo.

There should be a provision to reference datastore uri from a kubernets secret. Something like
``` yaml
replicaCount: 3
datastore: 
  engine: postgres
  refUriSecret: openfga-db-secret 
```   

openfga-db-secret.yaml
``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: openfga-db-secret
  namespace: openfga
type: Opaque
data:
  OPENFGA_DATASTORE_URI: dGVzdA==

```
