### ISSUE TITLE
OpenFGA returns unexpected "null" responses randomly

### ISSUE THREAD

**Issue by dlirai** [openfga/helm-charts#44]
I am using OpenFGA's HTTP API to perform authorization checks. I encounter a weird issue: some authorization check(s) may "randomly" receive "null" as the response, instead of "true" or "false". (I would assume that for every check, the server should return either "true" or "false".) This could happen in all of the following three scenarios:

- Scenario 1: Use OpenFGA along with the integrated Postgres database that is launched with the official Helm chart. The OpenFGA server along with the integrated Postgres database server is launched as follows:
```
helm install openfga openfga/openfga \
--set datastore.engine=postgres \
--set datastore.uri="postgres://postgres:password@openfga-postgresql.default.svc.cluster.local:5432/postgres?sslmode=disable" \
--set postgres.enabled=true \
--set postgresql.auth.postgresPassword=password \
--set postgresql.auth.database=postgres
```
The "null" responses are quite random. Sometimes, I get 1; sometimes I get 3; sometimes, I don't get any "null" response!! Also, it seems that having replicaCount=1 makes the issue almost impossible to happen. Having replicaCount=3 (the default value) or replicaCount=5 makes the issue more likely to happen.

- Scenario 2: Use OpenFGA with an independent Postgres database. The independent Postgres database server is launched as follows:
```
helm install dlpostgres \
    	--set auth.postgresPassword=password \
    	oci://registry-1.docker.io/bitnamicharts/postgresql
```
The OpenFGA server is launched as follows, using the official Helm chart:
```
helm install openfga openfga/openfga \
  		--set replicaCount=1 \
		--set log.level=error \
  		--set datastore.engine=postgres \
  		--set datastore.uri="postgres://postgres:password@dlpostgres-postgresql.default.svc.cluster.local:5432/postgres?sslmode=disable"
```
In general, in Scenario 2, the issue is more likely to happen compared to Scenario 1. Even with replicaCount=1, it is still very possible for the issue to happen. Usually, 3 or 5 out of 5000 authorization checks may receive "null" as the response.

- Scenario 3: Use OpenFGA along with Azure Postgres database server. I created the Azure Postgres database server first, and then launch the OpenFGA server using the official Helm chart as follows:
```
helm install openfga openfga/openfga \
  		--set replicaCount=1 \
		--set log.level=error \
  		--set datastore.engine=postgres \
  		--set datastore.uri="CONNECTION_STRING_FROM_AZURE_POSTGRES_DATABASE_SERVER"
```
The issue is even more likely to happen compared to Scenario 1 and Scenario 2. About 100 or even more checks will receive "null" as the response, compared to just a couple in Scenario 1 or 2.

Note that I was using the same model and data for the testings in all scenarios. The authorization checks that receive "null" as the response are different in different runs. Thus, I don't think it's the issue with my model or data. 

Besides, when I use an unofficial OpenFGA Helm chart here:
https://github.com/AlexandreBrg/openfga-helm
to do testings in Scenario 2 and Scenario 3, I never have the same issue. I.e., the unofficial OpenFGA Helm chart works correctly all the time!
Could someone help look into this issue?

**Comment by jon-whit** [comment]
@dlirai could you share the exact model, tuples, and requests that you are making that can reproduce this issue?

Also, what version of OpenFGA are you running? Are you just using the defaults from the Helm chart?

**Comment by dlirai** [comment]
Yes, I am using the defaults from the Helm chart.

**Comment by miparnisari** [comment]
@dlirai hi! Could you retry your test with the latest release and let me know if it improves things? https://github.com/openfga/helm-charts/releases/tag/openfga-0.1.23 

Also, when you test with more than 1 replica of OpenFGA, please note this: https://openfga.dev/docs/getting-started/running-in-production#database-recommendations

> The server setting OPENFGA_DATASTORE_MAX_OPEN_CONNS should be set to be equal to your database's max connections. For example, in Postgres, you can see this value via running the SQL query SHOW max_connections;. If you are running multiple instances of the OpenFGA server, you should divide this setting equally among the instances. For example, if your database's max_connections is 100, and you have 2 OpenFGA instances, OPENFGA_DATASTORE_MAX_OPEN_CONNS should be set to 50 for each instance.

**Comment by rhamzeh** [comment]
@dlirai - did you manage to retry? Did you encounter the same issue?

**Comment by mdnorman** [comment]
We are running into this as well lately. We aren't close to any redlines on the DB (CPU, memory, connections) or in the ECS container (CPU, memory).

**Comment by jeevanions** [comment]
Facing the same issue. 

[logs.txt](https://github.com/user-attachments/files/19536547/logs.txt)

**Comment by avinashs433** [comment]
Hi,

Are also experiencing this issue using v1.8.4 using 3 replica.

Regards,
Avinash

**Comment by JRDG** [comment]
> Facing the same issue. We are running `openfga/openfga:v1.8.7` image version and running single container (one replicaset with 1 instance.)
> 
> [logs.txt](https://github.com/user-attachments/files/19536547/logs.txt)

Im having the same issue. Only one replica, single container ,latest version.
@jeevanions could you find the root cause? 
I will create a new issue for my case adding more info
Thanks!

**Comment by kdbrooks** [comment]
I am also getting this error not using the helm chart running OpenFGA version 1.11.5 on an Azure VM and connecting to an Azure PostgreSQL Flexible server. Is Azure Postgres the common thread here?

It runs fine for a while then I get:

```
openfga[4110388]: {"level":"info","timestamp":1773356047.9917645,"msg":"grpc_req_complete","build.version":"v1.11.5","build.commit":"c9b9256ba5e84d4d4532a38ede931cbb84742463","grpc_service":"openfga.v1.OpenFGAService","grpc_method":"ListStores","grpc_type":"unary","user_agent":"python-httpx/0.28.1","raw_request":{"page_size":null,"continuation_token":"","name":""},"raw_response":{"code":"deadline_exceeded","message":"Request Deadline Exceeded"},"query_duration_ms":"3000","peer.address":"10.1.0.4:60796","request_id":"ce38faea-9e3f-4e97-b6bc-5f3647001e52","grpc_code":4004,"error":"rpc error: code = Code(4004) desc = Request Deadline Exceeded"}
```

Here is my config:

```yaml
datastore:
  engine: postgres
  uri: postgres://redacted:redacted@redacted.postgres.database.azure.com:5432/fga?sslmode=require
  maxOpenConns: 100
  minOpenConns: 20
  minIdleConns: 20
  connMaxIdleTime: 5m
  metrics:
    enabled: true
authn:
  method: preshared
  preshared:
    keys: ["redacted"]
playground:
  enabled: false
grpc:
  addr: fga.example.com:8083
  tls:
    enabled: true
    cert: /etc/letsencrypt/live/fga.example.com/fullchain.pem
    key: /etc/letsencrypt/live/fga.example.com/privkey.pem
http:
  addr: fga.example.com:8082
  tls:
    enabled: true
    cert: /etc/letsencrypt/live/fga.example.com/fullchain.pem
    key: /etc/letsencrypt/live/fga.example.com/privkey.pem
log:
  format: json
  level: info
metrics:
  enabled: true
  addr: 127.0.0.1:2112
  checkIteratorCache:
    enabled: true
  checkQueryCache:
    enabled: true
  cacheController:
    enabled: true
  requestTimeout: 10s
```

For me the only solve is to restart the openfga service.
