### ISSUE TITLE
Playground Not Disabled When Setting playground.enabled: false

### ISSUE THREAD

**Issue by mdimovskihtec** [openfga/helm-charts#54]
I am trying to install OpenFGA on my kubernetes cluster, having oidc as my authentication method.

My values file snippet is as follows:
```
...
authn:
  method: oidc
  oidc:
    audience: xxxxx
    issuer: https://login.microsoftonline.com/xxxxxx/v2.0

playground:
  enabled: false
...
```
I am receiving this error message from the container logs
`panic: the playground only supports authn methods 'none' and 'preshared'`

I suppose what is going on in the background is that the flag for disabling the playground is not propagated, and instead it picks up the default enabled flag.

Any help would be appreciated.
